### ISSUE TITLE
Should strip whitespace

### ISSUE THREAD

**Issue by FichteFoll** [makukha/pydantic-file-secrets#13]
The default implementation of `SecretsSettingsSource` strips the read file contents of any whitespace but this one here does not.

Setting `str_strip_whitespace` in the `model_config` does not seem to have any effect on this either.

**Comment by makukha** [comment]
Btw, I just checked that `str_strip_whitespace` is not respected by original `SecretsSettingsSource`:

```python
def test_str_strip_whitespace_not_respected(secrets_dir):
    class Settings(BaseSettings):
        key: str

        model_config = SettingsConfigDict(
            secrets_dir=secrets_dir,
            str_strip_whitespace=False,
        )

    secrets_dir.add_files(
        ('key', ' value '),
    )

    conf = Settings()
    assert conf.key == 'value'  # str_strip_whitespace not respected
```

**Comment by makukha** [comment]
@FichteFoll thank you for the bug report. The fix was trivial and already merged to main branch. I will update PyPi release as soon as all bugs reported will be fixed (a couple of days at most).

Thank you for your interest in the package!

**Comment by FichteFoll** [comment]
> Btw, I just checked that str_strip_whitespace is not respected by original SecretsSettingsSource:

Indeed, it was simply always stripped. I simply monkey-patched `FileSecretsSettingsSource.load_secrets` while waiting for a patch but will gladly remove it once the new version is out.

Thanks for adapting this into a package until this feature hopefully lands in the mainline pydantic-settings project.

**Comment by makukha** [comment]
> I simply monkey-patched `FileSecretsSettingsSource.load_secrets` while waiting for a patch but will gladly remove it once the new version is out.

The new [version 0.3.0](https://github.com/makukha/pydantic-file-secrets/releases/tag/0.3.0) with all your bug reports and suggestions is [released on PyPI](https://pypi.org/project/pydantic-file-secrets/0.3.0/).
Thank you for the feedback!

> Thanks for adapting this into a package until this feature hopefully lands in the mainline pydantic-settings project.

There's already a [PR](https://github.com/pydantic/pydantic-settings/pull/372) to `pydantic_settings` for multiple `secrets_dir` waiting to be merged. And yes, the plan is to update `pydantic_settings` with at least some of features from this package.
